### ISSUE TITLE
[Android] DragAndDropEndedCommand called before the item is reordered in the collection

### ISSUE THREAD

**Issue by InquisitorJax** [roubachof/Sharpnado.Presentation.Forms#71]
**Platform :**
 - OS: Android

**Description**
In the AndroidHorizontalListViewRenderer, line 120, the command is called before the list is reordered. This means when the handler for the command is executed, the list is still in the order before the drag and drop takes place.

### Fix
Move _onDragAndDropdEnded?.Execute(null); line to after the collection is modified.

**Comment by NickeManarin** [comment]
A simple workaround for this issue (if you can't wait for the fix) is to use the `ChildrenReordered` event from the `HorizontalListView`.

https://github.com/NickeManarin/Xamarin.Demos2/blob/82254e4adea77ad7ca48cf436961b52dc516f9af/TestApp/View/RegistrationSteps/PhotosView.xaml.cs#L120

In my case, I wanted to know when the list was reordered, in order to adjust the index numbers of each list item.
